CREATE TABLE estudantes (
    id SERIAL PRIMARY KEY,
    idade_grupo INTEGER, 
    sexo INTEGER,
    tipo_ensino_medio INTEGER,
    tipo_bolsa INTEGER, 
    trabalho_adicional INTEGER, 
    atividade_artistica_esportiva INTEGER, 
    tem_parceiro INTEGER, 
    salario_total INTEGER, 
    transporte_universidade INTEGER,
    tipo_acomodacoes_chipre INTEGER,
    educacao_mae INTEGER, 
    educacao_pai INTEGER, 
    numero_irmaos INTEGER, 
    status_parental INTEGER, 
    ocupacao_mae INTEGER, 
    ocupacao_pai INTEGER, 
    horas_de_estudo_semanais INTEGER, 
    frequencia_leitura_nao_cientifica INTEGER, 
    frequencia_leitura_cientifica INTEGER, 
    presenca_seminarios INTEGER, 
    impacto_projetos_sucesso INTEGER, 
    presenca_aulas INTEGER, 
    preparo_provas_midterm_1 INTEGER, 
    preparo_provas_midterm_2 INTEGER, 
    anotacoes_aulas INTEGER, 
    atencao_aulas INTEGER, 
    discussao_melhora_interesse INTEGER, 
    sala_de_aula_invertida INTEGER, 
    media_acumulada_ultimo_semestre INTEGER, 
    media_acumulada_esperada INTEGER, 
    id_curso INTEGER,
    nota_final INTEGER 
);